



export const GET_HOME_SUCCESS = 'GET_HOME_SUCCESS' ; 


export const GET_ACADEMY_SUCCESS = 'GET_ACADEMY_SUCCESS' ; 


export const GET_SINGLE_COURSE_PAGE_INFO_SUCCESS = 'GET_SINGLE_COURSE_PAGE_INFO_SUCCESS' ; 



export const LOGIN_PROCESS = 'LOGIN_PROCESS' ; 
export const LOGIN_PROCESS_SUCCESS = 'LOGIN_PROCESS_SUCCESS' ; 
export const LOGIN_PROCESS_FAILED = 'LOGIN_PROCESS_FAILED' ; 


export const GET_USER_DATA_SUCCESSED = 'GET_USER_DATA_SUCCESSED' ; 
export const GET_USER_DATA_FAILED = 'GET_USER_DATA_FAILED' ; 

export const LOG_OUT = 'LOG_OUT' ;
export const LOG_OUT_SUCCESS = 'LOG_OUT_SUCCESS' ;


export const REGISTER_COURE = 'REGISTER_COURE' ;
export const REGISTER_COURE_SUCCESSED = 'REGISTER_COURE_SUCCESSED' ;


export const GET_CAN_USE = 'GET_CAN_USE' ;
export const GET_CAN_USE_SUCCESS = 'GET_CAN_USE_SUCCESS' ;


export const RESET_AUTH_ERROR = 'RESET_AUTH_ERROR' ; 




export const TOKEN_EXPIERED = 'TOKEN_EXPIERED' ; 